#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : jupyter_core
Version  : 4.3.0
Release  : 6
URL      : https://pypi.python.org/packages/2f/39/5138f975100ce14d150938df48a83cd852a3fd8e24b1244f4113848e69e2/jupyter_core-4.3.0.tar.gz
Source0  : https://pypi.python.org/packages/2f/39/5138f975100ce14d150938df48a83cd852a3fd8e24b1244f4113848e69e2/jupyter_core-4.3.0.tar.gz
Summary  : Jupyter core package. A base package on which Jupyter projects rely.
Group    : Development/Tools
License  : BSD-3-Clause-Clear
Requires: jupyter_core-bin
Requires: jupyter_core-python
Requires: traitlets
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools
BuildRequires : traitlets
BuildRequires : traitlets-python

%description
# Jupyter Core
Core common functionality of Jupyter projects.
This package contains base application classes and configuration inherited by other projects.
It doesn't do much on its own.

%package bin
Summary: bin components for the jupyter_core package.
Group: Binaries

%description bin
bin components for the jupyter_core package.


%package python
Summary: python components for the jupyter_core package.
Group: Default

%description python
python components for the jupyter_core package.


%prep
%setup -q -n jupyter_core-4.3.0

%build
export LANG=C
export SOURCE_DATE_EPOCH=1488922241
python2 setup.py build -b py2
python3 setup.py build -b py3

%install
export SOURCE_DATE_EPOCH=1488922241
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot} --force
python3 -tt setup.py build -b py3 install --root=%{buildroot} --force

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/jupyter
/usr/bin/jupyter-migrate

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
